# Conduit
# Using 3xpo/alpine-conduit-base (unofficial, CI built image)

services:
  homeserver:
    image: docker.io/3xpo/alpine-conduit-base:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:6167:6167
    volumes:
      - db:/var/lib/matrix-conduit/
    environment:
      CONDUIT_SERVER_NAME: example.com # <- EDIT THIS
      CONDUIT_DATABASE_PATH: /var/lib/matrix-conduit/
      CONDUIT_DATABASE_BACKEND: rocksdb
      CONDUIT_PORT: 6167
      CONDUIT_MAX_REQUEST_SIZE: 20000000 # in bytes, ~20 MB
      CONDUIT_ALLOW_REGISTRATION: 'true'
      CONDUIT_ALLOW_FEDERATION: 'true'
      CONDUIT_ALLOW_CHECK_FOR_UPDATES: 'true'
      CONDUIT_TRUSTED_SERVERS: '["matrix.org"]'
      CONDUIT_MAX_CONCURRENT_REQUESTS: 100
  #
  ### Uncomment if you want to use your own Element-Web App.
  ### Note: You need to provide a config.json for Element and you also need a second
  ###       Domain or Subdomain for the communication between Element and Conduit
  ### Config-Docs: https://github.com/vector-im/element-web/blob/develop/docs/config.md
  # element-web:
  #   image: vectorim/element-web:latest
  #   restart: unless-stopped
  #   ports:
  #     - 8009:80
  #   volumes:
  #     - ./element_config.json:/app/config.json
  #   depends_on:
  #     - homeserver

volumes:
  db:
