# Github Publish Container Workflow
name: Publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Use Noble Repos
      #   run: |
      #     sudo sed -i s/jammy/noble/g /etc/apt/sources.list
      #     sudo apt update -y -qq
      # - name: Normal Upgrade
      #   run: sudo apt upgrade -y
      # - name: Dist Upgrade
      #   run: sudo apt dist-upgrade -y
      - name: Ensure Podman & Buildah are installed
        run: sudo apt install -y podman buildah

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bootstrap
        run: ./bootstrap

      - name: Configure
        run: ./configure --publish

      - name: Update Version Number
        run: ./img-tools/ci/set-version

      - name: Update CI-generated Metadata
        run: ./img-tools/ci/update-ci-instructions

      - name: Pull arch
        run: |
          podman pull docker.io/archlinux:latest

      - name: Pull alpine
        run: |
          podman pull docker.io/alpine:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build & Push Docker images
        run: |
          make build
