# Github Publish Container Workflow
name: Publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Buildah
        run: |
          curl -fsSL 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x0E98404D386FA1D9' -o /tmp/0x0E98404D386FA1D9.asc
          curl -fsSL 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x6ED0E7B82643E131' -o /tmp/0x6ED0E7B82643E131.asc
          sudo mv /tmp/0x0E98404D386FA1D9.asc /etc/apt/trusted.gpg.d/
          sudo mv /tmp/0x6ED0E7B82643E131.asc /etc/apt/trusted.gpg.d/
          sudo sh -c "echo 'deb http://deb.debian.org/debian sid main' >> /etc/apt/sources.list"
          sudo sh -c "echo 'deb-src http://deb.debian.org/debian sid main' >> /etc/apt/sources.list"
          sudo sh -c "echo 'Package: *' > /etc/apt/preferences.d/sid-pinning"
          sudo sh -c "echo 'Pin: release a=unstable' >> /etc/apt/preferences.d/sid-pinning"
          sudo sh -c "echo 'Pin-Priority: 100' >> /etc/apt/preferences.d/sid-pinning"
          sudo apt -y update
          sudo apt -y install buildah/sid podman/sid libc-bin/sid libc6/sid

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bootstrap
        run: |
          ./bootstrap

      - name: Pull arch
        run: |
          podman pull docker.io/archlinux:latest

      - name: Pull alpine
        run: |
          podman pull docker.io/alpine:latest

      - name: Build Docker images
        run: |
          pnpm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push to Docker Hub
        run: |
          pnpm ./img-tools/ci/publish
