# Github Publish Container Workflow
name: Publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upgrade System
        run: |
          set -eax
          sudo apt update -y -qq
          sudo apt install -y update-manager-core
          cat /etc/apt/sources.list
          echo '.d:'
          ls /etc/apt/sources.list.d/*
          cat /etc/apt/sources.list.d/*
          sudo do-release-upgrade

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bootstrap
        run: ./bootstrap

      - name: Configure
        run: ./configure --publish

      - name: Update Version Number
        run: ./img-tools/ci/set-version

      - name: Update CI-generated Metadata
        run: ./img-tools/ci/update-ci-instructions

      - name: Pull arch
        run: |
          podman pull docker.io/archlinux:latest

      - name: Pull alpine
        run: |
          podman pull docker.io/alpine:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build & Push Docker images
        run: |
          make build
