# Github Publish Container Workflow
name: Publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Bootstrap
        run: |
          ./bootstrap

      - name: Pull arch
        run: |
          podman pull docker.io/archlinux:latest

      - name: Pull alpine
        run: |
          podman pull docker.io/alpine:latest

      - name: Build Docker images
        run: |
          pnpm run build

      - name: Push to Docker Hub
        run: |
          pnpm ./img-tools/ci/publish
