name: Publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: '23 */2 * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # - name: Sid-ify
      #   run: |
      #     (curl -fL 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x0E98404D386FA1D9' -o /tmp/0x0E98404D386FA1D9.asc && sudo mv /tmp/0x0E98404D386FA1D9.asc /etc/apt/trusted.gpg.d/) &
      #     (curl -fL 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x6ED0E7B82643E131' -o /tmp/0x6ED0E7B82643E131.asc && sudo mv /tmp/0x6ED0E7B82643E131.asc /etc/apt/trusted.gpg.d/) &
      #     wait
      #     sudo sh -c "echo 'deb http://ftp.debian.org/debian sid main' >> /etc/apt/sources.list"
      #     sudo sh -c "echo 'deb-src http://ftp.debian.org/debian sid main' >> /etc/apt/sources.list"
      #     sudo sh -c "echo 'deb http://ftp.ch.debian.org/debian sid main' >> /etc/apt/sources.list"
      #     sudo sh -c "echo 'deb-src http://ftp.ch.debian.org/debian sid main' >> /etc/apt/sources.list"
      #     sudo sh -c "echo 'deb http://ftp.de.debian.org/debian sid main' >> /etc/apt/sources.list"
      #     sudo sh -c "echo 'deb-src http://ftp.de.debian.org/debian sid main' >> /etc/apt/sources.list"
      #     sudo sh -c "echo 'deb http://ftp.ca.debian.org/debian sid main' >> /etc/apt/sources.list"
      #     sudo sh -c "echo 'deb-src http://ftp.ca.debian.org/debian sid main' >> /etc/apt/sources.list"
      #     sudo apt update -y -qq

      - name: Run multiarch/qemu-user-static
        run: sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Install Dependencieis
        run: |
          set -eax
          sudo apt install build-essential libssl-dev git make bash jq -y
          sudo apt install podman buildah -y
          sudo apt install qemu-system -y
          sudo apt install qemu-user -y
          sudo apt install qemu-user-static binfmt-support -y

      - name: Enable Binfmt Support
        run: |
          sudo /usr/sbin/update-binfmts --enable

      - name: Tell git to shut up
        run: git config --global --add safe.directory /__w/containers/containers

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bootstrap
        run: ./bootstrap

      - name: Configure
        run: |
          sudo mkdir -p /usr/bin/rootful
          echo -e '#!/bin/bash\nsudo podman $@' | sudo tee /usr/bin/rootful/podman
          echo -e '#!/bin/bash\nsudo buildah $@' | sudo tee /usr/bin/rootful/buildah
          sudo chmod +x -R /usr/bin/rootful
          ./configure --arch=any -o=/usr/bin/rootful/podman -O=/usr/bin/rootful/buildah

      - name: Update Version Number
        run: ./img-tools/ci/set-version

      - name: Update CI-generated Metadata
        run: ./img-tools/ci/update-ci-instructions

      - name: Pull arch
        run: |
          sudo podman pull docker.io/archlinux:latest

      - name: Pull alpine
        run: |
          sudo podman pull docker.io/alpine:latest

      - name: Build OCI images
        run: |
          WRITE_TO_PUSH_SCRIPT=/tmp/deploy.sh pnpm build --output-style stream

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Publish Images
        run: |
          chmod +x /tmp/deploy.sh
          sudo /tmp/deploy.sh
