# Github Publish Container Workflow
name: Publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Buildah
        run: |
          set -eax
          sudo apt -y -qq update
          sudo apt -y install bats btrfs-progs git go-md2man golang libapparmor-dev libglib2.0-dev libgpgme11-dev libseccomp-dev libselinux1-dev make skopeo
          mkdir -p /tmp/a/b/c
          git clone https://github.com/containers/buildah /tmp/a/b/c/buildah
          cd /tmp/a/b/c/buildah
          make runc all SECURITYTAGS="apparmor seccomp"
          sudo make install install.runc
          buildah --help

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bootstrap
        run: |
          ./bootstrap

      - name: Pull arch
        run: |
          podman pull docker.io/archlinux:latest

      - name: Pull alpine
        run: |
          podman pull docker.io/alpine:latest

      - name: Build Docker images
        run: |
          pnpm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push to Docker Hub
        run: |
          pnpm ./img-tools/ci/publish
