# Github Publish Container Workflow
name: Publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      # we don't use ourselves here as that could cause softlocks when building
      image: archlinux/archlinux
    steps:
      - name: Setup Container
        run: pacman -Syu sudo nodejs git npm pnpm jq podman buildah bash make which --needed --noconfirm

      - name: Checkout
        uses: actions/checkout@v4

      - name: Bootstrap
        run: ./bootstrap

      - name: Configure
        run: ./configure --publish

      - name: Update Version Number
        run: ./img-tools/ci/set-version

      - name: Update CI-generated Metadata
        run: ./img-tools/ci/update-ci-instructions

      - name: Pull arch
        run: |
          podman pull docker.io/archlinux:latest

      - name: Pull alpine
        run: |
          podman pull docker.io/alpine:latest

      - name: Log in to Docker Hub
        run: podman login "-u=${{ secrets.DOCKER_HUB_USERNAME }}" "-p=${{ secrets.DOCKER_HUB_PASSWORD }}" docker.io

      - name: Build & Push Docker images
        run: |
          make build
