# Github Publish Container Workflow
name: Publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */2 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Sid-ify
        run: |
          (curl -fL 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x0E98404D386FA1D9' -o /tmp/0x0E98404D386FA1D9.asc && sudo mv /tmp/0x0E98404D386FA1D9.asc /etc/apt/trusted.gpg.d/) &
          (curl -fL 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x6ED0E7B82643E131' -o /tmp/0x6ED0E7B82643E131.asc && sudo mv /tmp/0x6ED0E7B82643E131.asc /etc/apt/trusted.gpg.d/) &
          wait
          sudo sh -c "echo 'deb http://ftp.debian.org/debian sid main' >> /etc/apt/sources.list"
          sudo sh -c "echo 'deb-src http://ftp.debian.org/debian sid main' >> /etc/apt/sources.list"
          sudo sh -c "echo 'deb http://ftp.ch.debian.org/debian sid main' >> /etc/apt/sources.list"
          sudo sh -c "echo 'deb-src http://ftp.ch.debian.org/debian sid main' >> /etc/apt/sources.list"
          sudo sh -c "echo 'deb http://ftp.de.debian.org/debian sid main' >> /etc/apt/sources.list"
          sudo sh -c "echo 'deb-src http://ftp.de.debian.org/debian sid main' >> /etc/apt/sources.list"
          sudo sh -c "echo 'deb http://ftp.ca.debian.org/debian sid main' >> /etc/apt/sources.list"
          sudo sh -c "echo 'deb-src http://ftp.ca.debian.org/debian sid main' >> /etc/apt/sources.list"
          sudo apt update -y -qq

      # - name: Run multiarch/qemu-user-static
      #   run: sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Install Dependencieis
        run: |
          set -eax
          sudo apt install build-essential libssl-dev git make bash jq -y
          sudo apt install podman/sid buildah/sid -y
          sudo apt install qemu-system/sid -y
          sudo apt install qemu-user/sid -y
          sudo apt install qemu-user-static/sid binfmt-support/sid -y

      - name: Enable Binfmt Support
        run: |
          sudo /usr/sbin/update-binfmts --enable

      - name: Tell git to shut up
        run: git config --global --add safe.directory /__w/containers/containers

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bootstrap
        run: ./bootstrap

      - name: Configure
        run: ./configure --publish --arch=any

      - name: Update Version Number
        run: ./img-tools/ci/set-version

      - name: Update CI-generated Metadata
        run: ./img-tools/ci/update-ci-instructions

      - name: Pull arch
        run: |
          podman pull docker.io/archlinux:latest

      - name: Pull alpine
        run: |
          podman pull docker.io/alpine:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build & Push Docker images
        run: |
          make build
